// 보관함 CRUD(Site/Category/Secret)·백업 도메인 에러 코드.
// 서버는 클라이언트 E2E 암호문을 패스스루하므로 복호화/잠금 관련 코드는 두지 않는다.
export const STORE_ERRORS = {
    SITE_NOT_FOUND: "SITE_NOT_FOUND",
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
    CATEGORY_SITE_MISMATCH: "CATEGORY_SITE_MISMATCH",
    SECRET_NOT_FOUND: "SECRET_NOT_FOUND",
    CIPHERTEXT_INCOMPLETE: "CIPHERTEXT_INCOMPLETE",
    IMPORT_CONFLICT: "IMPORT_CONFLICT",
    IMPORT_INVALID: "IMPORT_INVALID",
    EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
    EXPENSE_DUPLICATE: "EXPENSE_DUPLICATE",
    RECURRING_NOT_FOUND: "RECURRING_NOT_FOUND",
    CIPHERTEXT_INCOMPLETE_ASSET: "CIPHERTEXT_INCOMPLETE_ASSET",
    INVALID_MONTH: "INVALID_MONTH",
} as const
