// 보관함 도메인 에러 코드. 서버는 클라이언트 E2E 암호문을 패스스루하므로 복호화/잠금 관련 코드는 두지 않는다.
export const VAULT_ERRORS = {
    SITE_NOT_FOUND: "SITE_NOT_FOUND",
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
    CATEGORY_SITE_MISMATCH: "CATEGORY_SITE_MISMATCH",
    SECRET_NOT_FOUND: "SECRET_NOT_FOUND",
    CIPHERTEXT_INCOMPLETE: "CIPHERTEXT_INCOMPLETE",
    IMPORT_CONFLICT: "IMPORT_CONFLICT",
    IMPORT_INVALID: "IMPORT_INVALID",
} as const
