// 자산(가계부) 도메인 에러 코드.
export const ASSET_ERRORS = {
    EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
    EXPENSE_DUPLICATE: "EXPENSE_DUPLICATE",
    RECURRING_NOT_FOUND: "RECURRING_NOT_FOUND",
    CIPHERTEXT_INCOMPLETE_ASSET: "CIPHERTEXT_INCOMPLETE_ASSET",
    INVALID_MONTH: "INVALID_MONTH",
    INCOME_NOT_FOUND: "INCOME_NOT_FOUND",
    ASSET_CATEGORY_NOT_FOUND: "ASSET_CATEGORY_NOT_FOUND",
} as const
